[platformio]
default_envs = atoms3r

[env:atoms3r]
platform = espressif32@6.9.0
board = m5stack-atoms3
framework = arduino
monitor_speed = 115200

lib_deps =
  m5stack/M5Unified@0.2.19
  m5stack/M5GFX@0.2.26
  m5stack/M5Chain@1.0.8
  hideakitai/ArduinoOSC@0.6.0
  hideakitai/ArxContainer@0.7.0
  hideakitai/ArxSmartPtr@0.3.0
  hideakitai/ArxTypeTraits@0.3.2
  hideakitai/DebugLog@0.8.4
  bblanchon/ArduinoJson@6.21.6

build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DM5CHAINOSC_PLATFORMIO
