[platformio]
default_envs = atoms3r

[env:atoms3r]
platform = espressif32
board = m5stack-atoms3
framework = arduino
monitor_speed = 115200

lib_deps =
  m5stack/M5Unified
  https://github.com/m5stack/M5Chain.git
  hideakitai/ArduinoOSC
  bblanchon/ArduinoJson@^6.21.5

build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DM5CHAINOSC_PLATFORMIO
